export default [
  {
    id: 1,
    order: 1,
    question:
      'Аэропорт «Хьюстон Интерконтинентал» в Техасе получал множество жалоб от пассажиров, которые слишком долго ожидали свой багаж. Какую хитрость придумали, чтобы претензии прекратились?',
    answer:
      'Путь пассажиров от трапа до зала получения багажа увеличили. Время, которое люди раньше тратили на ожидание чемоданов, они стали проводить в дороге',
    cover: 'image:https://www.voltaaomundo.pt/files/2019/09/15-1-741x486_c.jpg',
    timer: 60,
    isActive: true,
    questionFontSize: 48,
    answerFontSize: 48,
  },
  {
    id: 2,
    order: 2,
    question:
      'В русскую баню с собой брали чистое белье, березовый веник и туесок квасу — не для питья. А для чего?',
    answer:
      'В словаре было написано: «Овёс — это зерно, которым в Англии кормят лошадей, а в Шотландии — людей». Значит, в чёрном ящике именно он',
    cover: 'image:https://www.voltaaomundo.pt/files/2019/09/15-1-741x486_c.jpg',
    timer: 60,
    isActive: true,
    questionFontSize: 48,
    answerFontSize: 48,
  },
  {
    id: 3,
    order: 3,
    question:
      'Уровень воды в пресноводном озере Баринго в Кении в самые жаркие дни не опускается, а поднимается. Из-за чего это происходит?',
    answer:
      'Уровень воды поднимается из-за того, что животные приходят в жару туда купаться',
    cover: 'image:https://www.voltaaomundo.pt/files/2019/09/15-1-741x486_c.jpg',
    timer: 60,
    isActive: true,
    questionFontSize: 48,
    answerFontSize: 48,
  },
  {
    id: 4,
    order: 4,
    question:
      'Стюардессы, останавливаясь в отеле между рейсами, обязательно кладут в сейф документы. В одной из авиакомпаний существует негласное правило, которое предписывает сотрудницам класть в сейф ещё один предмет. Какой?',
    answer:
      'Это туфли. Без них стюардесса точно не выйдет из номера и заодно возьмёт документы',
    cover: 'image:https://www.voltaaomundo.pt/files/2019/09/15-1-741x486_c.jpg',
    timer: 60,
    isActive: true,
    questionFontSize: 48,
    answerFontSize: 48,
  },
  {
    id: 5,
    order: 5,
    question:
      'Карикатурист Эшли Бриллиант справедливо полагает, что жить на земле дорого, зато каждый из нас ежегодно получает бесплатный круиз. Что это за круиз?',
    answer: 'Answer',
    cover: 'image:https://www.voltaaomundo.pt/files/2019/09/15-1-741x486_c.jpg',
    timer: 60,
    isActive: true,
    questionFontSize: 48,
    answerFontSize: 48,
  },
  {
    id: 6,
    order: 6,
    question:
      'Бразильский футбольный клуб «Витория» из города Салвадор в 2012 году устроил интересную акцию. Футболисты вышли на поле в форме, на которой вместо привычных красных полос были белые. Через несколько дней одна белая полоса снова стала красной, потом ещё одна, и так постепенно команда вновь принялась играть в традиционной форме. Что за акцию проводил клуб?',
    answer: 'Answer',
    cover: 'image:https://www.voltaaomundo.pt/files/2019/09/15-1-741x486_c.jpg',
    timer: 60,
    isActive: true,
    questionFontSize: 48,
    answerFontSize: 48,
  },
  {
    id: 7,
    order: 7,
    question:
      'На что только не идут владельцы супермаркетов ради увеличения прибыли! В европейской сети магазинов руководство специально поручило выложить пол мелкой плиткой в отделах с дорогими товарами. Для чего?',
    answer: 'Answer',
    cover: 'image:https://www.voltaaomundo.pt/files/2019/09/15-1-741x486_c.jpg',
    timer: 60,
    isActive: true,
    questionFontSize: 48,
    answerFontSize: 48,
  },
  {
    id: 8,
    order: 8,
    question:
      'Учёный представил своё изобретение миру в 1809 году, но получил награду в 12 тысяч франков только через восемь месяцев. Что он изобрёл?',
    answer: 'Answer',
    cover: 'image:https://www.voltaaomundo.pt/files/2019/09/15-1-741x486_c.jpg',
    timer: 60,
    isActive: true,
    questionFontSize: 48,
    answerFontSize: 48,
  },
  {
    id: 9,
    order: 9,
    question:
      'В одной японской компании действует необычное правило: сотрудники сами определяют надбавку к своей зарплате. Максимальный бонус - 6%, но это если повезет. С помощью какого предмета происходит определение надбавки?',
    answer: 'Answer',
    cover: 'image:https://www.voltaaomundo.pt/files/2019/09/15-1-741x486_c.jpg',
    timer: 60,
    isActive: true,
    questionFontSize: 48,
    answerFontSize: 48,
  },
  {
    id: 10,
    order: 10,
    question:
      'Кого решили изобразить на плакатах против расизма, потому что они и белые, и чёрные, и азиаты?',
    answer: 'Answer',
    cover: 'image:https://www.voltaaomundo.pt/files/2019/09/15-1-741x486_c.jpg',
    timer: 60,
    isActive: true,
    questionFontSize: 48,
    answerFontSize: 48,
  },
  {
    id: 11,
    order: 11,
    question:
      'Длинный по-китайски - «чхан», город - «чхен». А что китайцы называют «чханчхе»?',
    answer: 'Answer',
    cover: 'image:https://www.voltaaomundo.pt/files/2019/09/15-1-741x486_c.jpg',
    timer: 60,
    isActive: true,
    questionFontSize: 48,
    answerFontSize: 48,
  },
  {
    id: 12,
    order: 12,
    question:
      'На олимпиаде в первом классе дети решали такую задачу: «Продолжите последовательность: 4, 3, 3, 6, 4, 5, …, …, …». Что нужно вставить на место пропусков?',
    answer: 'Answer',
    cover: 'image:https://www.voltaaomundo.pt/files/2019/09/15-1-741x486_c.jpg',
    timer: 60,
    isActive: true,
    questionFontSize: 48,
    answerFontSize: 48,
  },
  {
    id: 13,
    order: 13,
    question:
      'Когда Уолт Дисней построил первый парк развлечений, билеты на предлагаемые им аттракционы оказались дороже, чем у конкурентов. Что придумал Уолт Дисней для того, чтобы люди покупали его более дорогие билеты?',
    answer: 'Answer',
    cover: 'image:https://www.voltaaomundo.pt/files/2019/09/15-1-741x486_c.jpg',
    timer: 60,
    isActive: true,
    questionFontSize: 48,
    answerFontSize: 48,
  },
  {
    id: 14,
    order: 14,
    question:
      'Индонезийскую бабочку аттакус атлас очень трудно поймать, не повредив её большие ломкие крылья. А перевозить — ещё сложнее. Как энтомологи всё же умудряются заполучить неповреждённых бабочек для коллекций и зоопарков?',
    answer: 'Answer',
    cover: 'image:https://www.voltaaomundo.pt/files/2019/09/15-1-741x486_c.jpg',
    timer: 60,
    isActive: true,
    questionFontSize: 48,
    answerFontSize: 48,
  },
  {
    id: 15,
    order: 15,
    question:
      'Френку Донеллану принадлежит рекорд Австралии — 130 метров. Рекорд в чем?',
    answer: 'Answer',
    cover: 'image:https://www.voltaaomundo.pt/files/2019/09/15-1-741x486_c.jpg',
    timer: 60,
    isActive: true,
    questionFontSize: 48,
    answerFontSize: 48,
  },
  {
    id: 16,
    order: 16,
    question:
      'Англичанин У.Джонсон предложил новое средство от храпа: как только человек начинает храпеть, реле включает магнитофон с любимой музыкой храпящего. Громкость звука постепенно нарастает, но как только храп прекращается, выключается и музыка. Из-за чего человек перестает храпеть?',
    answer: 'Answer',
    cover: 'image:https://www.voltaaomundo.pt/files/2019/09/15-1-741x486_c.jpg',
    timer: 60,
    isActive: true,
    questionFontSize: 48,
    answerFontSize: 48,
  },
];
